slug = "90sKid"
title = "90s Kid"
author = "Caolinn"
value = 10
description = """Twist it! Turn it! Pull it! Reverse Engineer [it](90sKid.png)! """
tags = ["dynamic"]
files = ["90sKid.png"]
flag = "flag{bop}"
enabled = true
