slug = "minibomb"
title = "Minibomb"
author = "loltyler1dotcom-discount-code-alpha"
value = 80
description = """Someone has planted a bomb on campus. [Here](minibomb) is a copy of the program controlling the bomb. We also found some partial source code of the program [here](minibomb.c). It is your job to use the source code along with various reverse engineering tools to examine the stack and find out the password to defuse the bomb. Hint: to input bytes into the program use python -c 'print(insert bytes)' | ./program"""
tags = [ "dynamic" ]
files = [ "minibomb","minibomb.c" ]
flag = "flag{3xpl0IteD}"
enabled = true
