id = 6
title ="Psi Beta Rho"
short = "PBR" 
date = "Fridays 6-8 pm"
description = """Want to be a hacker? ğŸ’» Come join Psi Beta Rho, ACM Cyber's competitive CTF team! ğŸ¥³CTFs or Capture-the-Flags are competitions where you solve cybersecurity problems to earn points. ğŸ’¯This is a great opportunity to add to your resume and build on the skills you have learned at Cyber Academy! ğŸ“„ ğŸ˜All skill levels and experiences are welcome! Be sure to invite your friends! ğŸ¥³ If you have any questions, be sure to join the ACM Cyber Discord to ask.
"""
link = ""
slides = ""
