slug = "password"
title = "password"
author = "james"
value = 15
description = "The government has hired you to crack the passcode of the executable in order to obtain the secret passphrase, supposedly a pie vendor has hidden some information inside, can you find the flag? If you run into permission problems, run <chmod 777 passcode>"
tags = [ "dynamic analysis" ]
files = [ "passcode" ]
flag = "flag{want_a_pie?}"
enabled = true
