slug = "assembly-feedback"
title = "Intro to Assembly & Reverse Engineering Feedback"
author = "Juliet"
value = 5
description = """Please fill out the [feedback form](https://forms.gle/EPd6ZS7RdwWasuW28)! We read all your responses to improve our future workshops :)"""
tags = ["assembly"]
files = []
flag = "flag{th4nk5_f0r_ATTeNDing!}"
enabled = true